# Site settings
name: f1ok.co
description: A curated list of companies hiring International Students on F1 visa.
maintainers:
  - shashisp

plugins:
  - jekyll-assets
  - kramdown
  - uglifier

# Social settings
github: shashisp/f1ok.co

# Build settings
source: src
destination: www
markdown: kramdown

compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier
